services:
  deephaven:
    image: ghcr.io/deephaven/server:${VERSION:-latest}
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g -Dauthentication.psk=Cr@shC0urse

  examples:
    image: ghcr.io/deephaven/examples:${VERSION:-latest}
    volumes:
      - ./data:/data
    command: initialize
